"""initial: full schema v1.0

Revision ID: 000f78bbf966
Revises: 
Create Date: 2026-07-02 23:07:20.309427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000f78bbf966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs_m8',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='UUID 字符串'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='search / read / write / sandbox / submit / login / logout / register / share / invite'),
    sa.Column('action_detail', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('current_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_m8_user_type_time', 'activity_logs_m8', ['user_id', 'action_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_m8_user_id'), 'activity_logs_m8', ['user_id'], unique=False)
    op.create_table('integrity_checks_m8',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_uid', sa.String(length=64), nullable=False),
    sa.Column('scope_user_id', sa.String(length=36), nullable=True),
    sa.Column('scope_date_from', sa.DateTime(), nullable=True),
    sa.Column('scope_date_to', sa.DateTime(), nullable=True),
    sa.Column('total_logs', sa.Integer(), nullable=False),
    sa.Column('verified_logs', sa.Integer(), nullable=False),
    sa.Column('broken_chains', sa.Integer(), nullable=False),
    sa.Column('anomalies', sa.Integer(), nullable=False),
    sa.Column('hash_chain_status', sa.String(length=20), nullable=False, comment='HEALTHY / DEGRADED / BROKEN'),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_checks_m8_report_uid'), 'integrity_checks_m8', ['report_uid'], unique=True)
    op.create_table('sandbox_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_uid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False, comment='python / r'),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued / pulling / running / completed / failed / timeout / killed'),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('cpu_seconds_used', sa.Float(), nullable=True),
    sa.Column('memory_peak_mb', sa.Float(), nullable=True),
    sa.Column('gpu_seconds_used', sa.Float(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_jobs_job_uid'), 'sandbox_jobs', ['job_uid'], unique=True)
    op.create_index(op.f('ix_sandbox_jobs_user_id'), 'sandbox_jobs', ['user_id'], unique=False)
    op.create_table('workspaces_m7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False, comment='school / college / lab / class / friends'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='UUID 字符串，关联 users.id'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['workspaces_m7.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_m7_owner_id'), 'workspaces_m7', ['owner_id'], unique=False)
    op.create_table('algorithms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('docker_image', sa.String(length=255), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('default_params', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_author_id'), 'algorithms', ['author_id'], unique=False)
    op.create_index(op.f('ix_algorithms_category'), 'algorithms', ['category'], unique=False)
    op.create_table('invitations_m7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invitation_code', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False, comment='UUID 字符串'),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('invitee_phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending / accepted / declined / expired'),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces_m7.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_m7_invitation_code'), 'invitations_m7', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_invitations_m7_workspace_id'), 'invitations_m7', ['workspace_id'], unique=False)
    op.create_table('workspace_members_m7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='UUID 字符串'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='super_admin / admin / leader / member / viewer'),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces_m7.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_m7')
    )
    op.create_index(op.f('ix_workspace_members_m7_user_id'), 'workspace_members_m7', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_m7_workspace_id'), 'workspace_members_m7', ['workspace_id'], unique=False)
    op.create_table('writing_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('journal_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('ai_generated_ratio', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_documents_user_id'), 'writing_documents', ['user_id'], unique=False)
    op.create_table('algorithm_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sandbox_job_id', sa.String(length=36), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued / running / completed / failed / timeout'),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['sandbox_job_id'], ['sandbox_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_executions_algorithm_id'), 'algorithm_executions', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_algorithm_executions_sandbox_job_id'), 'algorithm_executions', ['sandbox_job_id'], unique=False)
    op.create_index(op.f('ix_algorithm_executions_user_id'), 'algorithm_executions', ['user_id'], unique=False)
    op.create_table('algorithm_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('algorithm_id', 'user_id', name='uq_algorithm_review_user')
    )
    op.create_index(op.f('ix_algorithm_reviews_algorithm_id'), 'algorithm_reviews', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_algorithm_reviews_user_id'), 'algorithm_reviews', ['user_id'], unique=False)
    op.create_table('content_traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('ai_generated_text', sa.Text(), nullable=False),
    sa.Column('cited_paper_ids', sa.JSON(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['writing_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_traces_document_id'), 'content_traces', ['document_id'], unique=False)
    op.add_column('papers', sa.Column('search_source', sa.String(length=20), nullable=True))
    op.add_column('papers', sa.Column('full_text', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('papers', sa.Column('volume', sa.String(length=50), nullable=True))
    op.add_column('papers', sa.Column('issue', sa.String(length=50), nullable=True))
    op.add_column('papers', sa.Column('pages', sa.String(length=50), nullable=True))
    op.add_column('papers', sa.Column('citations_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_papers_search_source'), 'papers', ['search_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_search_source'), table_name='papers')
    op.drop_column('papers', 'citations_json')
    op.drop_column('papers', 'pages')
    op.drop_column('papers', 'issue')
    op.drop_column('papers', 'volume')
    op.drop_column('papers', 'relevance_score')
    op.drop_column('papers', 'full_text')
    op.drop_column('papers', 'search_source')
    op.drop_index(op.f('ix_content_traces_document_id'), table_name='content_traces')
    op.drop_table('content_traces')
    op.drop_index(op.f('ix_algorithm_reviews_user_id'), table_name='algorithm_reviews')
    op.drop_index(op.f('ix_algorithm_reviews_algorithm_id'), table_name='algorithm_reviews')
    op.drop_table('algorithm_reviews')
    op.drop_index(op.f('ix_algorithm_executions_user_id'), table_name='algorithm_executions')
    op.drop_index(op.f('ix_algorithm_executions_sandbox_job_id'), table_name='algorithm_executions')
    op.drop_index(op.f('ix_algorithm_executions_algorithm_id'), table_name='algorithm_executions')
    op.drop_table('algorithm_executions')
    op.drop_index(op.f('ix_writing_documents_user_id'), table_name='writing_documents')
    op.drop_table('writing_documents')
    op.drop_index(op.f('ix_workspace_members_m7_workspace_id'), table_name='workspace_members_m7')
    op.drop_index(op.f('ix_workspace_members_m7_user_id'), table_name='workspace_members_m7')
    op.drop_table('workspace_members_m7')
    op.drop_index(op.f('ix_invitations_m7_workspace_id'), table_name='invitations_m7')
    op.drop_index(op.f('ix_invitations_m7_invitation_code'), table_name='invitations_m7')
    op.drop_table('invitations_m7')
    op.drop_index(op.f('ix_algorithms_category'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_author_id'), table_name='algorithms')
    op.drop_table('algorithms')
    op.drop_index(op.f('ix_workspaces_m7_owner_id'), table_name='workspaces_m7')
    op.drop_table('workspaces_m7')
    op.drop_index(op.f('ix_sandbox_jobs_user_id'), table_name='sandbox_jobs')
    op.drop_index(op.f('ix_sandbox_jobs_job_uid'), table_name='sandbox_jobs')
    op.drop_table('sandbox_jobs')
    op.drop_index(op.f('ix_integrity_checks_m8_report_uid'), table_name='integrity_checks_m8')
    op.drop_table('integrity_checks_m8')
    op.drop_index(op.f('ix_activity_logs_m8_user_id'), table_name='activity_logs_m8')
    op.drop_index('idx_audit_m8_user_type_time', table_name='activity_logs_m8')
    op.drop_table('activity_logs_m8')
    # ### end Alembic commands ###
