"""add_paper_uid_and_user_fields

Revision ID: d844407f6050
Revises: 4cf596d046a2
Create Date: 2026-07-04 00:25:51.319689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd844407f6050'
down_revision: Union[str, None] = '4cf596d046a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('activity_logs', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('activity_logs', 'resource_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    op.alter_column('annotations', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('annotations', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('annotations', 'paper_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('content_traces', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('content_traces', 'document_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('coupons', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('documents', 'parent_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    op.alter_column('invoices', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('invoices', 'payment_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    op.alter_column('model_providers', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.add_column('papers', sa.Column('paper_uid', sa.String(length=64), nullable=True, comment='文献唯一标识，格式 paper_{uuid前8位}'))
    op.alter_column('papers', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.create_unique_constraint(None, 'papers', ['paper_uid'])
    op.alter_column('payments', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'subscription_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('sandbox_sessions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('sandbox_sessions', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('search_history', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subscriptions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('token_blacklist', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('token_blacklist', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_library', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_library', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_library', 'paper_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_model_configs', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_model_configs', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('user_model_configs', 'provider_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('wechat_union_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['wechat_union_id'])
    op.alter_column('workspace_members', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('workspace_members', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('writing_documents', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('writing_documents', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('writing_plans', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=False)
    op.alter_column('writing_plans', 'final_document_id',
               existing_type=sa.CHAR(length=32),
               type_=app.core.database.UniversalUUID(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writing_plans', 'final_document_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('writing_plans', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('writing_documents', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('writing_documents', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('workspaces', 'owner_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('workspace_members', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('workspace_members', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'wechat_union_id')
    op.drop_column('users', 'phone')
    op.alter_column('user_model_configs', 'provider_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_model_configs', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_model_configs', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_library', 'paper_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_library', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_library', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('token_blacklist', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('token_blacklist', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.alter_column('search_history', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sandbox_sessions', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('sandbox_sessions', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'subscription_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('payments', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'papers', type_='unique')
    op.alter_column('papers', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('papers', 'paper_uid')
    op.alter_column('model_providers', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'payment_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('documents', 'parent_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('documents', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('coupons', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('content_traces', 'document_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('content_traces', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('annotations', 'paper_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('annotations', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('annotations', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('activity_logs', 'resource_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('activity_logs', 'user_id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('activity_logs', 'id',
               existing_type=app.core.database.UniversalUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
